### PR TITLE
[ADDED] New schema for the `Timeline Edits.json` data from the google takeout

### PR DESCRIPTION
**Pull request by hossain-khan**
Google takeout now provides a new file. See https://www.reddit.com/r/GoogleMaps/comments/193vafa/google_maps_location_history_download_mystery_file/

Sample data https://github.com/hossain-khan/kgeo-timeline/issues/45#issuecomment-2002872346

Validated schema using AJV

```shell
ajv --spec=draft2020 --validate-formats=false --verbose=true --strict=true --all-errors=true validate -s .\schemas\TimelineEdits.schema.json -d .\schemas\timeline.json
```

### CODE REVIEW

**Comment by CarlosBergillos** [comment]
Thanks for sharing this and for working on the new schema.
It would defintely be very useful to include this in the project!

I validated your `TimelineEdits.schema.json` schema with a new export from me and it worked well. :)

Some comments:
- Can you use 4 space indentation in the schema files for consistency with the others?
- Can you update the `Makefile`  (add a new `timeline-edits` entry to `SOURCES` and `SOURCE_TITLES`) and update the `docs/reference/index.md` file, so that this new schema is also visible in the docs. Let me know if you need any help with this.
I recommend taking a look at: https://locationhistoryformat.com/contributing/#testing-locally if you want to test how the rendered pages will look like.

**Comment by CarlosBergillos** [comment]
The schema is missing some "title" and "description" fields, eg:
`Missing 'title' in '#/properties/timelineEdits/items' or '#/$defs/timelineEditsItem'`
`Missing 'title' in '#/$defs/timelineEditsItem/properties/deviceId'`
...

These fields are required to generate the markdown/html page from the schema. These errors appear when running `make build` (after updating the `Makefile`).

Can you address it?

Thanks!

**Comment by hossain-khan** [comment]
Yes, I can take a look into these comments. Thanks for checkout out. Will update the PR today or tomorrow.

**Comment by hossain-khan** [comment]
@CarlosBergillos I have updated the PR.

Unfortunately, I was not able to build using `make build` on local machine 

```
python -m tools.jsonschema_to_md schemas/Settings.schema.json -o docs/reference/settings.md -t "**\`Settings.json\`** Format Definition"
python: error: Failed to locate 'python'.
xcode-select: Failed to locate 'python', requesting installation of command line developer tools.
make: *** [docs/reference/settings.md] Error 72
```

I am running on MacOS and make version is 

```
make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

python --version
Python 3.9.6
```

Also `pip install tools` which did not help solve the issue.

**Comment by CarlosBergillos** [comment]
Ah, I can't test the build process in Mac so I can't help you with that unfortunately.

But thanks for the new changes!

Last things:
`Missing 'title' in '#/$defs/metadata/properties/platform'`
`Missing 'description' in '#/$defs/signal/properties/activityRecord/properties/detectedActivities/items'`
`Missing 'description' in '#/$defs/signal/properties/wifiScan/properties/devices/items'`
`Missing 'description' in '#/$defs/timelineEditsItem/properties/placeAggregates/properties/placeAggregateInfo/items'`

After you resolve these I'll merge the PR.

**Comment by hossain-khan** [comment]
@CarlosBergillos It should be good now.

Let me know if more references need to be updated in `Makefile` or `index.md`

**Comment by CarlosBergillos** [comment]
Merged! :D Thanks again for contributing!

The Timeline Edits docs are now live here:
https://locationhistoryformat.com/reference/timeline-edits/

I also updated the [General Structure](https://locationhistoryformat.com/guides/general-structure/) page to include it.
I still don't fully understand the purpose of this new file haha, so feel free to add some "context" information there, but not needed.

**Pull request merged**
